services:
  db:
    image: postgres:13
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    volumes:
      - estudo-spring-data-jpa:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  estudo-spring-data-jpa: